# linear and angular speed limits for the robot
max_v: 0.5 # m/s
max_w: 0.3 # rad/s
# observation rate fo the robot
frame_rate: 10 # Hz

# topic names (modify for different robots/nodes)
vel_navi_topic: "/cmd_vel"
